# Generated by Django 3.2.11 on 2024-01-16 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=200, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=200, null=True)),
                ('subscription_item_id', models.CharField(blank=True, max_length=200, null=True)),
                ('email_address', models.EmailField(max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
