# Generated by Django 5.2.4 on 2025-07-29 13:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_id', models.UUIDField(help_text='Unique ID for this specific run of the task.')),
                ('service', models.CharField(blank=True, max_length=50, null=True)),
                ('end_point', models.CharField(blank=True, max_length=50, null=True)),
                ('data_point', models.CharField(blank=True, max_length=50, null=True)),
                ('report_start_datetime', models.DateTimeField(blank=True, null=True)),
                ('report_end_datetime', models.DateTimeField(blank=True, null=True)),
                ('full_report', models.JSONField(help_text='Complete nested data report.')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('task', models.ForeignKey(help_text='Reference to the associated Task object.', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reporting.task')),
            ],
            options={
                'verbose_name': 'Task Report',
                'verbose_name_plural': 'Task Reports',
                'unique_together': {('run_id', 'task', 'data_point')},
            },
        ),
    ]
