# Generated by Django 5.2.4 on 2025-07-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_taskreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSummaryReportNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('total_critical_events', models.IntegerField(default=0)),
                ('critical_events_summary', models.JSONField(blank=True, default=list)),
                ('total_login_attempts', models.IntegerField(default=0)),
                ('successful_logins', models.IntegerField(default=0)),
                ('failed_logins', models.IntegerField(default=0)),
                ('total_login_time', models.FloatField(default=0.0)),
                ('total_2fa_attempts', models.IntegerField(default=0)),
                ('total_2fa_successes', models.IntegerField(default=0)),
                ('total_2fa_failures', models.IntegerField(default=0)),
                ('total_2fa_time', models.FloatField(default=0.0)),
                ('total_attempt_failed', models.IntegerField(default=0)),
                ('attempt_failed_errors', models.JSONField(blank=True, default=list)),
                ('failed_attempt_error_logs', models.JSONField(blank=True, default=list)),
                ('login_exceptions_summary', models.JSONField(blank=True, default=list)),
                ('login_exceptions_count', models.IntegerField(default=0)),
                ('page_detection_exceptions_summary', models.JSONField(blank=True, default=list)),
                ('page_detection_exceptions_count', models.IntegerField(default=0)),
                ('locate_element_exceptions_summary', models.JSONField(blank=True, default=list)),
                ('locate_element_exceptions_count', models.IntegerField(default=0)),
                ('page_load_details', models.JSONField(blank=True, default=dict)),
                ('total_reports_considered', models.IntegerField(default=0)),
                ('first_report_datetime', models.DateTimeField(blank=True, null=True)),
                ('last_report_datetime', models.DateTimeField(blank=True, null=True)),
                ('has_next_page_info', models.BooleanField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_alerted_at', models.DateTimeField(blank=True, null=True)),
                ('latest_task_status', models.CharField(blank=True, max_length=255, null=True)),
                ('latest_login_status', models.CharField(blank=True, max_length=64, null=True)),
                ('latest_report_start_datetime', models.DateTimeField(blank=True, null=True)),
                ('latest_report_end_datetime', models.DateTimeField(blank=True, null=True)),
                ('latest_total_task_runtime', models.FloatField(default=0.0)),
                ('run_id_of_latest_report', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Task Summary Report',
                'verbose_name_plural': 'Task Summary Reports',
                'ordering': ['-updated_at'],
            },
        ),
    ]
