# Generated by Django 5.2.4 on 2025-08-01 06:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_tasksummaryreportnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
