# Generated by Django 5.2.4 on 2025-08-05 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_alter_taskreport_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksummaryreportnew',
            name='task_id',
        ),
        migrations.AddField(
            model_name='tasksummaryreportnew',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_summary_report', to='reporting.task'),
        ),
    ]
