# Generated by Django 5.2.4 on 2025-08-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_remove_tasksummaryreportnew_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksummaryreportnew',
            name='failed_downloads_details',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tasksummaryreportnew',
            name='failed_to_download_file_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tasksummaryreportnew',
            name='found_next_page_info_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tasksummaryreportnew',
            name='has_billing_exception',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasksummaryreportnew',
            name='next_page_info_not_found_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tasksummaryreportnew',
            name='specific_exception_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tasksummaryreportnew',
            name='storage_upload_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasksummaryreportnew',
            name='task_completion_status',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tasksummaryreportnew',
            name='total_downloaded_files',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tasksummaryreportnew',
            name='total_storage_uploads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tasksummaryreportnew',
            name='total_users_scraped',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tasksummaryreportnew',
            name='has_next_page_info',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
